apiVersion: v1
kind: Service
metadata:
 name: nginx-deployment
spec:
 type: NodePort
 selector:
   app: nginx-deployment
 ports:
   - port: 8090
     targetPort: 80
---     
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx-deployment
 template:
   metadata:
     labels:
       app: nginx-deployment
   spec:
     containers:
     - name: nginx
       image: nginx
       ports:
       - containerPort: 80